### ISSUE TITLE
Default SURF index should be 0 if no SURF is applied to geometry

### ISSUE THREAD

**Issue by rmcdermo** [firetools/blenderfds#14]
[FLAME.blend.txt](https://github.com/firetools/blenderfds/files/6792527/FLAME.blend.txt)

In the attached scenario, the "Test_Facility" has not been assigned a SURF.  Therefore the SURF index for each FACE should be 0.  That is, the FACES array should be
```
FACES=2,3,1,0,....
```
Instead, we are getting
```
FACES=2,3,1,1,...
```
This is a problem now that Marcos has fixed a bug that checks the number of SURFs on each GEOM line (we were getting away with it before).

**Comment by emanuelegissi** [comment]
Ok, let me check

**Comment by emanuelegissi** [comment]
I fixed it. In current BF, a GEOM Object should always have referenced SURFs.

**Comment by rmcdermo** [comment]
@emanuelegissi Sorry, but still not working.  When I load the `cad/Sandia_FLAME_Facility/FLAME.blend` file, select `Test_Facility`, and click the `FDS Code` button, I get this error:
<img width="557" alt="Screen Shot 2021-08-05 at 9 58 34 AM" src="https://user-images.githubusercontent.com/4418497/128362836-cbf67127-2f62-4c54-b614-d1a7337d71bf.png">

Additionally, whenever I click the `FDS Geometry` button, I see a new object "Test_Facility_GEOM_tmp" show up in the collection, which I do not think we want.  Please see below

<img width="1433" alt="Screen Shot 2021-08-05 at 9 56 11 AM" src="https://user-images.githubusercontent.com/4418497/128363040-bb7177a7-f4e6-4907-80d1-d5c8f6d3993a.png">

**Comment by rmcdermo** [comment]
Just to be clear, the behavior I would expect is that if I do not select a Material slot, then BlenderFDS should assign 0 (INERT) for the SURF_ID.

**Comment by emanuelegissi** [comment]
Ok, I am trying again ;-)

Il giorno gio 5 ago 2021 alle ore 16:02 Randy McDermott <
***@***.***> ha scritto:

**Comment by emanuelegissi** [comment]
Exporting to GEOM should work now as you asked, let's check importing

**Comment by rmcdermo** [comment]
Hi Ema,
OK, the SURF_ID issue seems to be fixed, but now I get a MOVE_ID added to the GEOM.  This should not be needed.  Notice that the MOVE line corresponds to the Z translation of the object.  But this should just be internal to Blender, not something that gets exported to FDS geometry.

<img width="875" alt="Screen Shot 2021-08-05 at 11 52 48 AM" src="https://user-images.githubusercontent.com/4418497/128381714-65a6d539-1f4e-43c1-b002-48a24940aa85.png">

**Comment by emanuelegissi** [comment]
That MOVE line slipped into the code because I am experimenting on
exporting the repeating bingeoms only once (eg many identical chairs around
a table).

The algorithm should check if the bingeom is used more than once, and only
in that case push the MOVE line.

I am going to fix that in the next couple of hours... you are really on the
edge now.

(I am going to use git branches for new features next time)

**Comment by emanuelegissi** [comment]
Ok, I pushed a quick fix. The MOVE line is not exported if not requested
and not necessary for repeated bingeoms.
I need to refactor that, in the next days


Il giorno gio 5 ago 2021 alle ore 19:23 Emanuele Gissi <
***@***.***> ha scritto:

**Comment by rmcdermo** [comment]
Seems to work now.  Though, when I first pulled up the case the "MOVE_ID" checkbox was checked by default.  Please make sure this is something the user explicitly adds.  (Should be unchecked by default)  Thanks!

**Comment by emanuelegissi** [comment]
Ok, it is done in master.

Il giorno ven 6 ago 2021 alle ore 20:55 Randy McDermott <
***@***.***> ha scritto:

**Comment by rmcdermo** [comment]
Great.  Yes, I tested and latest master branch works great.  Thank you!
